version: '3.8'

services:
  # Flask Python Backend
  backendtest:
    build: .
    container_name: backendtest
    security_opt:
      # Disable AppArmor
      - apparmor:unconfined  
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: bookreview_DB
    ports:
    # to use this port when connecting to front end
      - 7000:7000
    depends_on:
      - db
    volumes:
      - .:/app

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookreview_DB
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
    # 3305 is actual mySQL port, 3306 is internal docker port
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
